services:
    PHPhinderBundle\Command\SchemaGenerateCommand:
        arguments:
            $schemaGenerator: '@PHPhinderBundle\Schema\SchemaGenerator'
        tags:
            - { name: 'console.command' }

    PHPhinderBundle\Schema\SchemaGenerator:
        class: PHPhinderBundle\Schema\SchemaGenerator
        arguments:
            $cacheDir: '%kernel.cache_dir%/phphinder'

    PHPhinderBundle\EventListener\SchemaListener:
        arguments:
            $schemaGenerator: '@PHPhinderBundle\Schema\SchemaGenerator'
        tags:
            -
                name: 'doctrine.event_listener'
                event: 'loadClassMetadata'

    PHPhinderBundle\EventListener\EntityListener:
        arguments:
            $schemaGenerator: '@PHPhinderBundle\Schema\SchemaGenerator'
        tags:
            -
                name: 'doctrine.event_listener'
                event: 'postPersist'
            -
                name: 'doctrine.event_listener'
                event: 'postUpdate'


